server:
  port: 8081

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    Asia/Shanghai 选择 中国标准时间 也可以选择UTC (但是UTC会慢8小时) 全球标准时间
    #  mysql 启动时的 偶发性 错误 java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
    #  解决方案 &allowPublicKeyRetrieval=true 博客文章 https://cloud.tencent.com/developer/news/791903
    url: jdbc:mysql://127.0.0.1:3306/cloud-payment?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址。单机版本使用这个地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

mybatis-plus:
  #  https://www.mybatis-plus.com/config/#mapperlocations  官方文档配置详解
  mapper-locations: classpath*:/mapper/**/*.xml
  # 设置别名 这样在 xml 当中就不需要在 写实体类的全路径
  type-aliases-package: com.dkz.springcloud.payment.entity
  configuration:
  # 开启mybatis的日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
