server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心 ， 动态创建路由的功能 ， 利用微服务名进行路由
          enabled: true
      routes:
        # 路由id ，没有固定规则 ， 但是要求全局唯一 ，建议配合服务名
        - id: payment_routh
        # 匹配后 ， 提供的服务的路由地址 , 使用注册中心
          uri: lb://CLOUD-PAYMENT-SERVICE
        # 断言 路径匹配进行路由
          predicates:
            - Path=/payment/**
            # 如果时间在这个之后 那么访问这个地址 ，延迟上线可以这也使用  测试 curl localhost:9527/payment/getById/1
            - After=2022-08-05T15:27:03.658+08:00[Asia/Shanghai]
            # 一定要带上 cookie username=dkz  curl localhost:9527/payment/getById/1 --cookie "username=dkz"
            - Cookie=username, dkz
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址。单机版本使用这个地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/




